# Generated by Django 5.2.17 on 2026-09-06 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0008_guest_booking_issue_guest_language_and_more'),
        ('messaging', '0005_message_source_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThankYouAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=160)),
                ('template_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thank_you_action', to='bookings.tour')),
            ],
        ),
        migrations.CreateModel(
            name='ThankYouDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_demo', models.BooleanField(default=False)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mytours.thankyouaction')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='messaging.contact')),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.guest')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.message')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('action', 'contact'), name='one_thank_you_per_tour_contact')],
            },
        ),
    ]
