# Generated by Django 5.2.17 on 2026-09-07 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_guest_booking_issue_guest_language_and_more'),
        ('mytours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thankyouaction',
            name='kind',
            field=models.CharField(default='closing', max_length=20),
        ),
        migrations.AddField(
            model_name='thankyouaction',
            name='request_key',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='thankyouaction',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to='bookings.tour'),
        ),
        migrations.AddConstraint(
            model_name='thankyouaction',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['closing', 'photos'])), fields=('tour', 'kind'), name='one_quick_message_per_tour'),
        ),
    ]
