# Generated by Django 5.2.17 on 2026-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytours', '0002_thankyouaction_kind_thankyouaction_request_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thankyoudelivery',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
