# Generated by Django 5.2.17 on 2026-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_inbound_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_inbound_channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp')], max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='preferred_channel',
            field=models.CharField(choices=[('auto', 'Automatic'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp_opted_in',
            field=models.BooleanField(default=False),
        ),
    ]
