# Generated by Django 5.2.17 on 2026-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_contact_last_inbound_at_contact_last_inbound_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_inbound_channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Prefer E.164, e.g. +12125551234.', max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], default='sms', max_length=20),
        ),
    ]
