# Generated by Django 5.2.17 on 2026-09-08 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_source_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('endpoint', models.URLField(max_length=2048, unique=True)),
                ('keys', models.JSONField()),
                ('previews', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error', models.CharField(blank=True, max_length=160)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messaging.message')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.pushdevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'message'), name='unique_push_message_device')],
            },
        ),
    ]
