# Generated by Django 5.2.17 on 2026-09-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0002_remove_messagetemplate_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='system_key',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
