# Generated by Django 5.2.17 on 2026-09-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_templates', '0004_group_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='email_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='separate_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
