# Generated by Django 5.2.17 on 2026-09-06 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0006_tourproduct_guest_adults_guest_attendance_overridden_and_more'),
        ('messaging', '0004_message_sender_name_message_sent_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='guruwalk', max_length=32, unique=True)),
                ('account_id', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=False)),
                ('auth_status', models.CharField(default='unknown', max_length=20)),
                ('auth_checked_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='never', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('worker_seen_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('imported_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VendorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('source', models.JSONField(default=dict)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bookings.guest')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.connection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='vendor_booking_identity')],
            },
        ),
        migrations.CreateModel(
            name='VendorEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('source', models.JSONField(default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.connection')),
                ('departure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bookings.tour')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='vendor_event_identity')],
            },
        ),
        migrations.CreateModel(
            name='VendorGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.connection')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='messaging.contact')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='vendor_guest_identity')],
            },
        ),
        migrations.CreateModel(
            name='VendorTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.connection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.tourproduct')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='vendor_tour_identity')],
            },
        ),
    ]
