# Generated by Django 5.2.17 on 2026-09-06 19:29

import django.db.models.deletion
from django.db import migrations, models


def link_existing_bookings_to_events(apps, schema_editor):
    VendorBooking = apps.get_model("integrations", "VendorBooking")
    VendorEvent = apps.get_model("integrations", "VendorEvent")
    Guest = apps.get_model("bookings", "Guest")
    for vendor_booking in VendorBooking.objects.filter(event__isnull=True).iterator():
        guest = Guest.objects.get(pk=vendor_booking.booking_id)
        event = VendorEvent.objects.filter(
            connection_id=vendor_booking.connection_id,
            departure_id=guest.booked_tour_id,
        ).first()
        if event:
            VendorBooking.objects.filter(pk=vendor_booking.pk).update(event_id=event.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='future_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='future_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='today_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='today_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='tomorrow_last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connection',
            name='tomorrow_last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='integrations.vendorevent'),
        ),
        migrations.RunPython(link_existing_bookings_to_events, migrations.RunPython.noop),
    ]
