# Generated by Django 5.2.17 on 2026-09-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_tour_fingerprint'),
        ('integrations', '0004_connection_sync_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendortour',
            name='name',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='vendorevent',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_events', to='bookings.tour'),
        ),
        migrations.AlterField(
            model_name='vendortour',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.tourproduct'),
        ),
    ]
