# Generated by Django 5.2.17 on 2026-09-06 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('is_admin', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('start_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='guest_profile', to='messaging.contact')),
                ('booked_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='bookings.tour')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
