# Generated by Django 5.2.17 on 2026-09-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='welcome_channel',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=20),
        ),
        migrations.AddField(
            model_name='guest',
            name='welcome_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='welcome_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('local', 'Local only'), ('failed', 'Failed'), ('unavailable', 'No contact method')], default='pending', max_length=20),
        ),
    ]
