# Generated by Django 5.2.17 on 2026-09-06 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_guest_welcome_channel_guest_welcome_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='attendance',
            field=models.CharField(choices=[('expected', 'Expected'), ('present', 'Attended'), ('absent', 'No-show')], default='expected', max_length=16),
        ),
        migrations.AddField(
            model_name='guest',
            name='tour_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='report',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tours', to=settings.AUTH_USER_MODEL),
        ),
    ]
