# Generated by Django 5.2.17 on 2026-09-06 18:00

from django.db import migrations, models


def restore_booked_status(apps, schema_editor):
    apps.get_model('bookings', 'Guest').objects.filter(attendance='absent').update(attendance='expected')


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_guest_attendance_guest_tour_notes_tour_report_and_more'),
    ]

    operations = [
        migrations.RunPython(restore_booked_status, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='guest',
            name='attendance',
            field=models.CharField(choices=[('expected', 'Booked'), ('present', 'Checked in'), ('canceled', 'Canceled')], default='expected', max_length=16),
        ),
    ]
