# Generated by Django 5.2.17 on 2026-09-06 21:24

from django.db import migrations, models
from django.db.models import F


def copy_current_party_counts(apps, schema_editor):
    guest_model = apps.get_model("bookings", "Guest")
    guest_model.objects.update(
        original_adults=F("adults"),
        original_children=F("children"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_tourproduct_guest_adults_guest_attendance_overridden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='feedback',
            field=models.CharField(choices=[('none', 'No feedback'), ('up', 'Thumbs up'), ('down', 'Thumbs down')], default='none', max_length=8),
        ),
        migrations.AddField(
            model_name='guest',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guest',
            name='original_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='guest',
            name='original_children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guest',
            name='party_size_overridden',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(copy_current_party_counts, migrations.RunPython.noop),
    ]
