# Generated by Django 5.2.17 on 2026-09-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_guest_feedback_guest_is_manual_guest_original_adults_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='booking_issue',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='language',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='guest',
            name='special_requests',
            field=models.TextField(blank=True),
        ),
    ]
