# Generated by Django 5.2.17 on 2026-09-07 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_guest_booking_issue_guest_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rescheduled_from',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_booking', to='bookings.guest'),
        ),
    ]
