# Generated by Django 5.2.17 on 2026-09-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_guest_rescheduled_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='fingerprint',
            field=models.CharField(editable=False, max_length=64, null=True, unique=True),
        ),
    ]
